USE [local_db]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20211203-175806]    Script Date: 07.12.2021 19:50:39 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20211203-175806] ON [dbo].[Group_union]
(
	[course] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


